### ISSUE TITLE
No .plasmoid file contained

### ISSUE THREAD

**Issue by jonnycat5000** [wwjjbb/Luna-II#13]
The README file in Luna-II/package states installation uses the "Luna-II-<ver>.plasmoid" file, but no *.plasmoid file is contained within either the git files or the downloadable *.zip file (Luna-II-master.zip).

**Comment by wwjjbb** [comment]
The instructions are unfortunately missing some details about the plasmoid
file. I sort of lost interest in the cmake stuff as Luna II is just qml and
js.

The plasmoid file is simply a zip of the package directory, renaming ".zip"
to ".plasmoid".

* Unpack the archive downloaded from github.

* Open terminal command line at the top level of unpacked tree.

* Run: ./mkzip

* This will create the plasmoid file if you have zip installed on PATH.

However, its probably easier to get Luna II from the KDE Store via Plasma

* Right click Plasma desktop,
* Add Widgets...
* Get New Widgets...
* Download New Plasma Widgets
* Search for Luna

**Comment by jonnycat5000** [comment]
Perfect, thank you so much that was the explanation I needed.
