### ISSUE TITLE
Support on Ubuntu 16.04

### ISSUE THREAD

**Issue by ghost** [wwjjbb/Luna-II#3]
wwjbb, are you sure you need QtQuick.Layouts version 1.3? This way, for those stuck on LTS like me, the Luna II widget won't work until 18.04... which is unfortunate as both the old Luna widgets no longer work also.

BTW I have a suggestion for a possible (new) widget: show (last, next) sunrise and sunset (and possibly moonrise and moonset too) times. This information is currently absent from any widget, including calendar ones. All it's required to compute it are user latitude, longitude and date/time/TZ.

**Comment by wwjjbb** [comment]
I've just tried with Layouts 1.2 and there was no problem. Will change it later.

With Luna II, I left all the calculations as they were.  Replacing them with e.g. suncalc.js (github mourner/suncalc.js) would be an improvement and supply rise/set times (and more). I've used suncalc in a plasmoid clone of kweather (kde3) and that bit  'just works'.

**Comment by wwjjbb** [comment]
@phptools, can you try 2.0.2

**Comment by ghost** [comment]
Sorry, but I receive the following error with 2.0.2:

Error while loading QML file: file:///home/andrea/.local/share/plasma/plasmoids/org.kde.userbase.plasma.luna-ii/contents/ui/main.qml:50:14: Cannot assign to non-existent property "toolTipItem"

**Comment by wwjjbb** [comment]
Thats from Plasma - I have version 5.29.0 (i.e. KDE Framework), the toolTipItem docs say it arrived in 5.19. Looking at he history on my PC, looks like it went with qt 5.4.

**Comment by wwjjbb** [comment]
toolTipItem replaced - using the plasmoid default tooltip instead.

**Comment by ghost** [comment]
Yep. My (default) most recent plasma-framework on 16.04 is version 5.18.0-0ubuntu1.1 (xenial-updates).

**Comment by ghost** [comment]
It works now - though window contents are almost invisible (I'll open a separate issue for that).
