### ISSUE TITLE
Window colors on Kubuntu 16.04 with dark themes

### ISSUE THREAD

**Issue by ghost** [wwjjbb/Luna-II#4]
The white background color makes text and buttons almost unreadable. My theme is breeze-dark.

![screenshot_20170324_211615](https://cloud.githubusercontent.com/assets/7521845/24312288/335a6eaa-10d8-11e7-874b-8216976e1da8.png)

**Comment by wwjjbb** [comment]
I found what was stopping the theme stuff working and made changes which seem ok in plasmoidviewer.

**Comment by ghost** [comment]
It works. Thank you!
